---
#
#
#
- hosts: localhost
  connection: local
  
  vars_files:
  - 'AWS.yml'
  
  tasks:
  - name: create ec2 instance in AWS account
    amazon.aws.ec2_instance:
      instance_type: t3.small
      image_id: ami-0dda7e535b65b6469
      count: 1
      region: "{{ aws_region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      network:
        assign_public_ip: true
        security_group: default
        vpc_subnet_id: subnet-22aba37b
      state: present
      tags:
        app_type: web-server
        

        
        
