---
# EC2 Provisioning Playbook
#
#
- hosts: localhost
  connection: local
  
  vars_files:
  - 'AWS.yml'
  
  tasks:
  - name: Security group creation
    amazon.aws.ec2_security_group:
      name: "{{ ec2_server_name }}-sg"
      description: sg with inbound rules
      region: "{{ aws_region }}"
      rules:
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80
          - proto: tcp
          ports:
          - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: allow ssh on port 22
      
  - name: create ec2 instance in AWS account
    amazon.aws.ec2_instance:
      name: "{{ ec2_server_name }}"
      instance_type: "{{ ec2_instance_type }}"
      image_id: "{{ image_id_number }}"
      key_name: "aap"
      count: 1
      region: "{{ aws_region }}"
      network:
        assign_public_ip: true
        security_group: "{{ ec2_server_name }}-sg"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
      state: present
      tags:
        app_type: web-server
        name: "{{ ec2_server_name }}"
        

        
        
