---
# EC2 Provisioning Playbook
#
#
- hosts: localhost
  connection: local
  
  vars_files:
  - 'AWS.yml'
  
  tasks:
  - name: create ec2 instance in AWS account
    amazon.aws.ec2_instance:
      name: "{{ ec2_server_name }}"
      instance_type: "{{ ec2_instance_type }}"
      image_id: "{{ image_id_number }}"
      key_name: "aap"
      count: 1
      region: "{{ aws_region }}"
      network:
        assign_public_ip: true
        security_group: default
        vpc_subnet_id: "{{ vpc_subnet_id }}"
      state: present
      tags:
        app_type: web-server
        

        
        
